import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./providers";

import './globals.css'
import Footer from '@/components/Footer';
import BottomNavigationbar from '@/components/Bottombar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-zinc-50'>
      <body className={inter.className}>
      <Providers>
          {children}
          <BottomNavigationbar />
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
