import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { red } from "@mui/material/colors";
import { StyledEngineProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import './globals.css'
import Footer from '@/components/Footer';
import BottomNavigationbar from '@/components/Bottombar';
import theme from '@/theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-zinc-50'>
      <body className={inter.className}>
      <ThemeProvider theme={theme}>
          {children}
      <BottomNavigationbar />
      <Footer/>
      </ThemeProvider>
      </body>
    </html>
  );
}
